name: Lint and Type Check
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Format checks
        run: pnpm run format
      - name: Lint checks
        run: pnpm run lint
      - name: Type checks
        run: pnpm tsc --noEmit
